name: bump_version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "The type of bump to perform."
        required: true
        type: choice
        default: patch
        options:
          - "patch"
          - "minor"
          - "major"

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BUMP_TOKEN }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: cache dependencies
        run: deno cache -r ./scripts/bump-version.ts

      - name: Run bump
        id: bump_version
        run: deno run -A ./scripts/bump-version.ts ${{ github.event.inputs.bump-type }} --github >> $GITHUB_OUTPUT

      - name: Show version
        run: echo "Updated to version ${{ steps.bump_version.outputs.VERSION }}"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        if: ${{ steps.bump_version.outputs.VERSION != '' }}
        with:
          message: "Bump ${{ github.event.inputs.bump-type }} version to: ${{ steps.bump_version.outputs.VERSION }}"
          add: "version.ts"
          author_name: "David Pires"
          author_email: "developer@davidpires.pt"